name: Format and tests the code in this repo
on:
  workflow_dispatch:
jobs:
  test:
    steps:
    - uses: actions/checkout@v3
    - uses: gcarreno/setup-lazarus@v3.2
    - with:
        lazarus-version: "stable"
        with-cache: true
    - run: lazbuild RoninLauncher.lpi
