on:
  pull_request:
    types:
    - closed

jobs:
  report_loc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: PavanMudigonda/lines-of-code-reporter@v1.5
